Order service & postgre sql
EugeneKaravanov/Ecommerce-platform pull request #3
Opened 2024-11-13 19:44 UTC by EugeneKaravanov

2024-12-05 12:57 UTC, pimushkin requested changes
Ты проделал большую работу! Молодец! Оставил небольшие комментарии с правками. Они весьма быстро правятся

Пропустим пока то, что нет таблицы и миграций для Customer, как и `ICustomerRepository` и `CustomerRepository`. Потом может быть добавим, как `CustomerServiceGRPC` вместе с CRUD эндпоинтам для клиентов

2024-12-05 12:57 UTC, pimushkin commented on Ecommerce/OrderService/Repositories/OrderRepository.cs
> +            cancellationToken.ThrowIfCancellationRequested();
Вызывать `cancellationToken.ThrowIfCancellationRequested()` избыточно, если следом у тебя сразу следом есть асинхронный метод, который принимает токен отмены.

Для лучшего понимания как работать с `CancellationToken`, я рекомендую ознакомиться с рекомендациями из данной статьи: https://medium.com/@mitesh_shah/a-deep-dive-into-c-s-cancellationtoken-44bc7664555f#:~:text=patterns%20as%20well.-,Recommended%20Patterns%20for%20Cancellation%20Tokens,-I%20wish%20I

2024-12-05 12:57 UTC, pimushkin commented on Ecommerce/OrderService/Repositories/OrderRepository.cs
> +            transaction.Commit();
У тебя начинается транзакция через `var transaction = conection.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);`, затем в конце метода ты вызываешь `transaction.Commit()`. Когда ты так делаешь, тебе нужно убедиться, что при возникновении ошибки или исключения транзакция будет откатана. Сейчас нет никакого **try/catch** блока, который бы при неудаче вызвал `transaction.Rollback()`. В идеале, стоит использовать что-то вроде такого:

```csharp
using var transaction = await conection.BeginTransactionAsync(cancellationToken);
try
{
    // тут твой запрос к базе
    await transaction.CommitAsync(cancellationToken);
}
catch
{
    await transaction.RollbackAsync(cancellationToken);
    throw;
}
```

2024-12-05 12:57 UTC, pimushkin commented on Ecommerce/OrderService/Repositories/OrderRepository.cs
В методах `GetOrdersAsync`, `GetOrderAsync` и `GetOrdersByCustomerAsync` ты также начинаешь транзакции (`var transaction = conection.BeginTransaction(System.Data.IsolationLevel.RepeatableRead);`) для чтения данных, но нигде их явно не коммитишь и не ролбэчишь, и они не обёрнуты в `using`. Даже при чтении, если ты хочешь зафиксировать состояние для repeatable read, стоит использовать `using` и в конце явно выполнять `transaction.Commit()` или `transaction.Rollback()`

2024-12-05 12:57 UTC, pimushkin commented on Ecommerce/OrderService/Repositories/OrderRepository.cs
> +            var transaction = conection.BeginTransaction(System.Data.IsolationLevel.RepeatableRead);
Такое использование транзакций и уровня изоляции `RepeatableRead` для операций чтения не совсем рационально. Их применять есть смысл тогда, когда ты хочешь получить согласованный "срез" данных на момент начала транзакции. Тебе это может быть полезно для того, чтобы гарантировать, что все последующие `SELECT` запросы в рамках той же транзакции будут видеть одну и ту же картину данных, даже если в базе происходят изменения другими транзакциями. То есть это может быть оправдано лишь тогда, когда важна консистентность результата выборки при чтении набора связанных данных в условиях высокой конкуренции на запись (надеюсь, понятно выразился 😅)

Однако, если твоя цель в методе просто прочитать данные, а требования к изоляции не настолько строги, то такой код уже может быть избыточным. В большинстве случаев простые операции чтения можно выполнять без явного использования транзакции, так как по умолчанию в PostgreSQL каждый отдельный `SELECT` уже работает в рамках своей собственной "мини-транзакции". Если ты не пытаетешься зафиксировать моментальный снимок данных на длительный период или не нужна повторяемая читаемость, то тебе не нужен `using` для транзакции и достаточно просто открыть соединение и выполнить необходимые запросы через `QueryAsync`

2024-12-05 12:57 UTC, pimushkin commented on Ecommerce/OrderService/Repositories/OrderRepository.cs
> +                                                        VALUES (@Customerid, @Orderdate, @Totalammount)
Ты где-то пишешь totalamount через одно "m", а где-то через два. Переименуй **Totalammount** в **TotalAmount** и перепроверь во всех местах, чтобы потом ошибок связанных с опечаткой не возникало

2024-12-05 12:57 UTC, pimushkin commented on Ecommerce/OrderService/Repositories/OrderRepository.cs
> +            using var conection = new NpgsqlConnection(_сonnectionString);
connection пишется тоже с двумя "n", а не одной. Тоже лучше поправить во всех местах

2024-12-05 12:57 UTC, pimushkin commented on Ecommerce/OrderService/Repositories/OrderRepository.cs
> +            var transaction = conection.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);
`NpgsqlConnection` реализует `IAsyncDisposable`, как и `NpgsqlTransaction`. А `BeginTransaction` имеет асинхронную реализацию, так что можешь писать так:

```csharp
await using var connection = new NpgsqlConnection(_сonnectionString);

await connection.OpenAsync(cancellationToken);

using var transaction = await connection.BeginTransactionAsync(System.Data.IsolationLevel.ReadCommitted, cancellationToken);
```

2024-12-05 12:57 UTC, pimushkin commented on Ecommerce/ProductService/Repositories/ProductRepository.cs
> +                                    WHERE @Id = Id
Это не ошибка, но обычно порядок пишут как `WHERE Id = @Id`. Для читаемости и единообразия лучше придерживаться стандартного порядка Столбец = Параметр

2024-12-05 12:57 UTC, pimushkin commented on Ecommerce/ProductService/Repositories/ProductRepository.cs
Где-то ты используешь транзакции, где-то нет. Пересмотри код класса с учетом того, что я тебе написал про OrderRepository

2024-12-05 12:57 UTC, pimushkin commented on Ecommerce/ProductService/Repositories/ProductRepository.cs
> +                transaction);
Если `NameFilter` изначально `null`, то в результате в `NameFilter = $"%{request.NameFilter}%"` будет `"%%"`, что вернёт все записи. При таком подходе условие `@NameFilter IS null OR Name ILIKE @NameFilter` сработает только в случае, если ты действительно передашь `null` в параметр без интерполяции. Возможно, логичнее проверять `if (request.NameFilter == null) ...` и в этом случае установить параметр `NameFilter` в `null`, а не в `"%%"`

2024-12-11 10:36 UTC, EugeneKaravanov commented on Ecommerce/OrderService/Repositories/OrderRepository.cs
> +            using var conection = new NpgsqlConnection(_сonnectionString);
Исправлено

2024-12-11 10:46 UTC, EugeneKaravanov commented on Ecommerce/OrderService/Repositories/OrderRepository.cs
> +                                                        VALUES (@Customerid, @Orderdate, @Totalammount)
Исправлено

2024-12-11 10:47 UTC, EugeneKaravanov commented on Ecommerce/ProductService/Repositories/ProductRepository.cs
> +                                    WHERE @Id = Id
Исправлено

2024-12-12 13:17 UTC, EugeneKaravanov commented on Ecommerce/ProductService/Repositories/ProductRepository.cs
> +                transaction);
Исправлено

2024-12-12 14:19 UTC, EugeneKaravanov commented on Ecommerce/OrderService/Repositories/OrderRepository.cs
> +            cancellationToken.ThrowIfCancellationRequested();
Исправлено

2024-12-12 14:28 UTC, EugeneKaravanov commented on Ecommerce/OrderService/Repositories/OrderRepository.cs
> +            var transaction = conection.BeginTransaction(System.Data.IsolationLevel.RepeatableRead);
Исправлено

2024-12-12 14:32 UTC, EugeneKaravanov commented on Ecommerce/OrderService/Repositories/OrderRepository.cs
> +            var transaction = conection.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);
Исправлено

2024-12-12 14:32 UTC, EugeneKaravanov commented on Ecommerce/ProductService/Repositories/ProductRepository.cs
Исправлено

2024-12-12 14:41 UTC, EugeneKaravanov commented on Ecommerce/OrderService/Repositories/OrderRepository.cs
> +            transaction.Commit();
Исправлено

2024-12-24 10:14 UTC, pimushkin requested changes

2024-12-24 10:14 UTC, pimushkin commented on Ecommerce/GatewayService/Controllers/OrderController.cs
> +                return Ok(response.Message);
Перепутал. Должно быть наоборот

2024-12-24 10:19 UTC, pimushkin approved these changes

2024-12-24 10:19 UTC, merged