Commit # 1 (Объявление миграций, моделей, Connection Factory, репозит…
EugeneKaravanov/Ecommerce-platform pull request #4
Opened 2024-12-26 17:17 UTC by EugeneKaravanov

2025-01-18 16:23 UTC, pimushkin requested changes

2025-01-18 16:23 UTC, pimushkin commented on Ecommerce/OrderService.Models/ShardFactory.cs
> +            _shards.Add(new Shard(connectionStrings[1], new List<int> { 4, 5, 6, 7 }));
Сейчас жёстко зашит набор бакетов `{0,1,2,3}` и `{4,5,6,7}`. Для нашей домашки это нормально, но в продакшене имеет смысл сделать конфигурацию через `appsettings.json`, чтобы не менять код при изменении количества шардов или бакетов

2025-01-18 16:23 UTC, pimushkin commented on Ecommerce/OrderService/Program.cs
> +var deffaultConnectionString = builder.Configuration.GetConnectionString("DefaultConnection");
Небольшая опечатка. default с двумя f написал

2025-01-18 16:23 UTC, pimushkin commented on Ecommerce/OrderService/Repositories/ShardOrderRepository.cs
> +                }
Хорошо, что ты используешь транзакцию. Однако при перехвате ошибок в `catch` не логируется само исключение. Мы с тобой ещё не разбирали логирование, но давай уже начнём его добавлять в проект. Если ты будешь здесь логировать исключение, то тебе это поможет потом понимать причину неудачи

После `RollbackAsync()` обычно стоит пробросить исключение выше (или хотя бы вернуть `result.Status = Failure`), иначе сервис снаружи не узнает, что пошло не так

2025-01-18 16:23 UTC, pimushkin commented on Ecommerce/OrderService/Repositories/ShardOrderRepository.cs
> +            await bucketConnection.ExecuteAsync(sqlStringToInsertInCustomerIdGlobalIndex, new
Тут потенциально логическая ошибка: ты вызываешь `customerIdGlobalIndexConnection.OpenAsync()`, но выполняешь `ExecuteAsync` на `bucketConnection` (а не на `customerIdGlobalIndexConnection`). Скорее всего, опечатка

2025-01-18 16:23 UTC, pimushkin commented on Ecommerce/OrderService/Repositories/ShardOrderRepository.cs
> +                                                        SELECT id FROM insert_result";
Решение с IdCounter в отдельном бакете в целом рабочее. Одну из проблем, которую я вижу, это то, что при большом потоке заказов это место станет узким - все запросы к `Bucket1.IdCounter` выполняются последовательно, а не параллельно. В качестве альтернативы можно было бы использовать PostgreSQL-секвенцию (например, `CREATE SEQUENCE`). Но для нашего проекта как ты сделал тоже пойдет

2025-01-27 12:03 UTC, EugeneKaravanov commented on Ecommerce/OrderService.Models/ShardFactory.cs
> +            _shards.Add(new Shard(connectionStrings[1], new List<int> { 4, 5, 6, 7 }));
Исправлено

2025-01-27 12:03 UTC, EugeneKaravanov commented on Ecommerce/OrderService/Program.cs
> +var deffaultConnectionString = builder.Configuration.GetConnectionString("DefaultConnection");
Исправлено

2025-01-27 12:04 UTC, EugeneKaravanov commented on Ecommerce/OrderService/Repositories/ShardOrderRepository.cs
> +            await bucketConnection.ExecuteAsync(sqlStringToInsertInCustomerIdGlobalIndex, new
Исправлено

2025-01-27 12:04 UTC, EugeneKaravanov commented on Ecommerce/OrderService/Repositories/ShardOrderRepository.cs
> +                                                        SELECT id FROM insert_result";
Исправлено

2025-01-27 14:36 UTC, EugeneKaravanov commented on Ecommerce/OrderService/Repositories/ShardOrderRepository.cs
> +                }
Вероятно, исправлено

2025-01-28 15:36 UTC, pimushkin submitted a review, later dismissed

2025-01-28 15:38 UTC, pimushkin approved these changes

2025-01-28 15:41 UTC, merged